# Pytest configuration file

[pytest]


addopts = -v --strict-markers 
#addopts = --browser chromium --browser firefox --browser webkit
#addopts = -v --reruns 2
markers =
    smoke: critical tests
    regression: full regression tests
    

