name: Playwright Tests

on:
  push:
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Verify Docker
        run: docker --version

      - name: Verify Docker Compose
        run: docker compose version

      - name: Create .env file
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env

      - name: Build Docker image
        run: docker compose build

      - name: Run Playwright tests
        run: docker compose run tests

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/

      - name: Generate Allure report
        if: always()
        run: |
          npm install -g allure
          allure generate allure-results -o allure-report

      - name: Upload Allure report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/


  deploy:
    if: always()
    needs: test
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download Allure report
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: allure-report

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4