name: Playwright Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Verify Docker
        run: docker --version

      - name: Verify Docker Compose
        run: docker compose version

      - name: Create .env file
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env



      - name: Build Docker image
        run: docker compose build

      - name: Run Playwright tests
        run: docker compose run tests






      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/